"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Check, ChevronLeft, ChevronRight, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { BottomSheet } from "@/components/ui/bottom-sheet";
import { addDays, formatLocalDate, startOfWeek } from "@/lib/date";
import type { MealType, MealWeekData, PlannedMeal, Recipe } from "@/types/domain";
import { toggleMeal } from "@/features/today/actions";
import { deleteRecipe } from "../actions";
import { MealEditor } from "./meal-editor";
import { RecipeDetail } from "./recipe-detail";
import { RecipeForm } from "./recipe-form";

type Sheet = { kind: "recipe"; recipe: Recipe } | { kind: "meal"; date: string; type: MealType; meal?: PlannedMeal } | { kind: "library" } | { kind: "recipeForm"; recipe?: Recipe } | null;
const mealTypes: { type: MealType; label: string }[] = [{ type: "breakfast", label: "Petit déjeuner" }, { type: "lunch", label: "Déjeuner" }, { type: "dinner", label: "Dîner" }];

export function MealPlanner({ data, demo }: { data: MealWeekData; demo: boolean }) {
  const [sheet, setSheet] = useState<Sheet>(null);
  const [search, setSearch] = useState("");
  const days = Array.from({ length: 7 }, (_, index) => addDays(data.weekStart, index));
  const currentStart = startOfWeek(data.today);
  const filteredRecipes = useMemo(() => data.recipes.filter((recipe) => recipe.name.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr"))), [data.recipes, search]);
  const close = () => setSheet(null);
  return <>
    <header className="flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-brand">Planning</p><h1 className="text-3xl font-bold">Repas</h1></div><button onClick={() => setSheet({ kind: "library" })} className="h-11 rounded-xl bg-brand px-4 text-sm font-bold text-white">Mes recettes</button></header>
    {demo && <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">Mode aperçu · les modifications nécessitent Supabase.</p>}
    <div className="mt-5 flex items-center justify-between rounded-2xl bg-white p-2 shadow-card"><Link aria-label="Semaine précédente" href={`/meals?week=${addDays(data.weekStart, -7)}`} className="flex h-11 w-11 items-center justify-center rounded-xl"><ChevronLeft /></Link><div className="text-center"><b className="block text-sm">{formatLocalDate(data.weekStart, { day: "numeric", month: "short" })} – {formatLocalDate(addDays(data.weekStart, 6), { day: "numeric", month: "short", year: "numeric" })}</b>{data.weekStart !== currentStart && <Link href="/meals" className="text-xs font-semibold text-brand">Revenir à cette semaine</Link>}</div><Link aria-label="Semaine suivante" href={`/meals?week=${addDays(data.weekStart, 7)}`} className="flex h-11 w-11 items-center justify-center rounded-xl"><ChevronRight /></Link></div>
    <div className="mt-4 space-y-3">{days.map((date) => <section key={date} className={`rounded-2xl p-3 shadow-card ${date === data.today ? "border-2 border-brand bg-brand-soft/40" : "bg-white"}`}><div className="mb-3 flex items-baseline justify-between"><h2 className="font-bold capitalize">{formatLocalDate(date, { weekday: "long" })}</h2><span className={`text-xs ${date === data.today ? "font-bold text-brand" : "text-slate-400"}`}>{date === data.today ? "Aujourd’hui · " : ""}{formatLocalDate(date, { day: "numeric", month: "short" })}</span></div><div className="space-y-2">{mealTypes.map(({ type, label }) => {
      const meal = data.meals.find((item) => item.date === date && item.type === type);
      return <div key={type} className="flex min-h-16 items-center gap-2 rounded-xl bg-white p-2 ring-1 ring-slate-100"><span className="w-20 shrink-0 text-[11px] font-semibold text-slate-400">{label}</span>{meal ? <><button onClick={() => setSheet({ kind: "recipe", recipe: meal.recipe })} className="min-w-0 flex-1 text-left"><b className="block truncate text-sm">{meal.recipe.name}</b><span className="text-[11px] text-slate-500">{meal.recipe.calories} kcal · {meal.recipe.protein} g prot. · {meal.portions} part.</span>{meal.isLeftover && <span className="block text-[10px] font-semibold text-amber-700">Restes du dîner précédent</span>}</button><form action={toggleMeal}><input type="hidden" name="id" value={meal.id} /><input type="hidden" name="completed" value={String(meal.eaten)} /><button aria-label={meal.eaten ? "Marquer comme non mangé" : "Marquer comme mangé"} className={`flex h-11 w-11 items-center justify-center rounded-full ${meal.eaten ? "bg-brand text-white" : "border border-slate-200 text-slate-300"}`}><Check size={19} /></button></form><button aria-label="Modifier ce repas" onClick={() => setSheet({ kind: "meal", date, type, meal })} className="flex h-11 w-9 items-center justify-center text-slate-400"><Pencil size={17} /></button></> : <button onClick={() => setSheet({ kind: "meal", date, type })} className="flex min-h-11 flex-1 items-center justify-center gap-1 rounded-lg border border-dashed border-slate-200 text-xs font-semibold text-brand"><Plus size={16} /> Ajouter</button>}</div>;
    })}</div></section>)}</div>
    <BottomSheet open={sheet?.kind === "recipe"} title={sheet?.kind === "recipe" ? sheet.recipe.name : "Recette"} onClose={close}>{sheet?.kind === "recipe" && <RecipeDetail recipe={sheet.recipe} />}</BottomSheet>
    <BottomSheet open={sheet?.kind === "meal"} title={sheet?.kind === "meal" && sheet.meal ? "Modifier le repas" : "Ajouter un repas"} onClose={close}>{sheet?.kind === "meal" && <MealEditor date={sheet.date} type={sheet.type} meal={sheet.meal} recipes={data.recipes} done={close} />}</BottomSheet>
    <BottomSheet open={sheet?.kind === "library"} title="Mes recettes" onClose={close}>{sheet?.kind === "library" && <div className="max-h-[72dvh] overflow-y-auto"><div className="flex gap-2"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18} /><span className="sr-only">Rechercher</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher une recette" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3" /></label><button onClick={() => setSheet({ kind: "recipeForm" })} className="flex h-11 items-center gap-1 rounded-xl bg-brand px-3 text-sm font-bold text-white"><Plus size={17} /> Ajouter</button></div><div className="mt-4 space-y-2">{filteredRecipes.map((recipe) => <article key={recipe.id} className="flex items-center gap-2 rounded-xl border border-slate-100 p-3"><button onClick={() => setSheet({ kind: "recipe", recipe })} className="min-w-0 flex-1 text-left"><b className="block truncate text-sm">{recipe.name}</b><span className="text-xs text-slate-400">{recipe.calories} kcal · {recipe.protein} g prot.</span></button><button onClick={() => setSheet({ kind: "recipeForm", recipe })} aria-label={`Modifier ${recipe.name}`} className="h-11 w-11 text-brand"><Pencil className="mx-auto" size={18} /></button><form action={deleteRecipe}><input type="hidden" name="id" value={recipe.id} /><button disabled={recipe.isUsed} title={recipe.isUsed ? "Retirez d’abord cette recette du planning" : "Supprimer la recette"} aria-label={`Supprimer ${recipe.name}`} className="h-11 w-11 text-red-600 disabled:cursor-not-allowed disabled:text-slate-300"><Trash2 className="mx-auto" size={18} /></button></form></article>)}</div></div>}</BottomSheet>
    <BottomSheet open={sheet?.kind === "recipeForm"} title={sheet?.kind === "recipeForm" && sheet.recipe ? "Modifier la recette" : "Ajouter une recette"} onClose={close}>{sheet?.kind === "recipeForm" && <RecipeForm recipe={sheet.recipe} availableIngredients={data.ingredients} done={close} />}</BottomSheet>
  </>;
}
