"use client";

import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import type { IngredientAmount, Recipe } from "@/types/domain";
import { saveRecipe } from "../actions";

type EditableIngredient = Pick<IngredientAmount, "ingredientId" | "name" | "quantity" | "unit">;
const emptyIngredient = (): EditableIngredient => ({ ingredientId: "", name: "", quantity: 100, unit: "g" });

export function RecipeForm({ recipe, availableIngredients, done }: { recipe?: Recipe; availableIngredients: { id: string; name: string }[]; done: () => void }) {
  const [ingredients, setIngredients] = useState<EditableIngredient[]>(recipe?.ingredients ?? [emptyIngredient()]);
  const update = (index: number, patch: Partial<EditableIngredient>) => setIngredients((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  const field = "mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3";
  return <form action={saveRecipe} onSubmit={done} className="max-h-[72dvh] space-y-4 overflow-y-auto pr-1"><input type="hidden" name="id" value={recipe?.id ?? ""} /><input type="hidden" name="ingredients" value={JSON.stringify(ingredients)} />
    <label className="block text-sm font-semibold">Nom<input className={field} required name="name" defaultValue={recipe?.name} /></label><label className="block text-sm font-semibold">Description <span className="font-normal text-slate-400">(facultative)</span><textarea className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-3" name="description" defaultValue={recipe?.description} /></label>
    <div className="grid grid-cols-2 gap-3"><NumberField name="portions" label="Portions" value={recipe?.portions ?? 2} /><NumberField name="prepMinutes" label="Préparation (min)" value={recipe?.prepMinutes ?? 20} /><NumberField name="calories" label="Calories / part" value={recipe?.calories ?? 0} /><NumberField name="protein" label="Protéines (g)" value={recipe?.protein ?? 0} step="0.1" /><NumberField name="carbs" label="Glucides (g)" value={recipe?.carbs ?? 0} step="0.1" /><NumberField name="fat" label="Lipides (g)" value={recipe?.fat ?? 0} step="0.1" /></div>
    <div><div className="flex items-center justify-between"><h3 className="font-bold">Ingrédients</h3><button type="button" onClick={() => setIngredients((items) => [...items, emptyIngredient()])} className="flex h-11 items-center gap-1 text-sm font-semibold text-brand"><Plus size={18} /> Ajouter</button></div>{ingredients.map((item, index) => <div key={index} className="mb-2 rounded-xl bg-slate-50 p-3"><div className="flex gap-2"><select aria-label="Ingrédient existant" value={item.ingredientId} onChange={(event) => { const selected = availableIngredients.find((ingredient) => ingredient.id === event.target.value); update(index, { ingredientId: event.target.value, name: selected?.name ?? "" }); }} className="h-11 min-w-0 flex-1 rounded-lg border border-slate-200 bg-white px-2"><option value="">Nouvel ingrédient</option>{availableIngredients.map((ingredient) => <option key={ingredient.id} value={ingredient.id}>{ingredient.name}</option>)}</select><button type="button" aria-label="Retirer l’ingrédient" onClick={() => setIngredients((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="h-11 w-11 text-red-600"><Trash2 className="mx-auto" size={19} /></button></div>{!item.ingredientId && <input aria-label="Nom du nouvel ingrédient" placeholder="Nom" value={item.name} onChange={(event) => update(index, { name: event.target.value })} className="mt-2 h-11 w-full rounded-lg border border-slate-200 px-2" />}<div className="mt-2 grid grid-cols-2 gap-2"><input aria-label="Quantité" type="number" min="0.01" step="0.01" value={item.quantity} onChange={(event) => update(index, { quantity: Number(event.target.value) })} className="h-11 rounded-lg border border-slate-200 px-2" /><input aria-label="Unité" placeholder="g, ml…" value={item.unit} onChange={(event) => update(index, { unit: event.target.value })} className="h-11 min-w-0 rounded-lg border border-slate-200 px-2" /></div></div>)}</div>
    <label className="block text-sm font-semibold">Étapes <span className="font-normal text-slate-400">(une par ligne)</span><textarea required name="instructions" defaultValue={recipe?.instructions.join("\n")} className="mt-1 min-h-32 w-full rounded-xl border border-slate-200 p-3" /></label><button className="sticky bottom-0 h-12 w-full rounded-xl bg-brand font-bold text-white">Enregistrer la recette</button>
  </form>;
}

function NumberField({ name, label, value, step = "1" }: { name: string; label: string; value: number; step?: string }) { return <label className="text-xs font-semibold">{label}<input className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" required type="number" min="0" step={step} name={name} defaultValue={value} /></label>; }
